<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowRight, Database, Glasses, HardDrive, History, RefreshCw } from '@lucide/vue'
import { api } from '../api/client'
import type { Overview } from '../api/types'
const data=ref<Overview|null>(null);const error=ref('')
const storage=computed(()=>data.value?`${(data.value.storage_bytes/1024/1024).toFixed(1)} MB`:'—')
async function load(){data.value=await api.overview()}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><section><header class="page-header"><div><p class="eyebrow">运行状态</p><h1>概览</h1></div><button class="icon-button" aria-label="刷新" title="刷新" @click="load"><RefreshCw :size="18"/></button></header><p v-if="error" class="error-banner">{{ error }}</p><div v-if="data" class="overview-grid"><div><Database :size="18"/><span>数据集图片</span><strong>{{ data.datasets.image_count }}</strong><small>{{ data.datasets.pending_count }} 张待复核</small></div><div><Glasses :size="18"/><span>当前模型</span><strong>{{ data.active_model?'已启用':'未启用' }}</strong><small>{{ data.active_model?.name||'请先完成训练' }}</small></div><div><History :size="18"/><span>检测记录</span><strong>{{ data.detection_counts.total }}</strong><small>图片 {{ data.detection_counts.image }} · 快照 {{ data.detection_counts.camera }}</small></div><div><HardDrive :size="18"/><span>本地存储</span><strong>{{ storage }}</strong><small>{{ data.resources.filter(r=>r.ready).length }}/{{ data.resources.length }} 项资源就绪</small></div></div><div v-if="data" class="overview-bands"><section><div class="section-heading"><h2>最近训练</h2><RouterLink to="/training">查看<ArrowRight :size="14"/></RouterLink></div><div v-if="data.latest_training" class="overview-run"><strong>{{ data.latest_training.state }}</strong><span>{{ data.latest_training.settings.epochs }} 轮 · {{ data.latest_training.settings.image_size }} px</span></div><div v-else class="empty-inline">暂无训练任务</div></section><section><div class="section-heading"><h2>最近评估</h2><RouterLink to="/models">模型库<ArrowRight :size="14"/></RouterLink></div><div v-if="data.latest_evaluation" class="overview-eval"><div><span>mAP@0.5</span><strong>{{ data.latest_evaluation.map50.toFixed(3) }}</strong></div><div><span>Precision</span><strong>{{ data.latest_evaluation.precision.toFixed(3) }}</strong></div><div><span>Recall</span><strong>{{ data.latest_evaluation.recall.toFixed(3) }}</strong></div></div><div v-else class="empty-inline">暂无评估结果</div></section></div></section></template>
